# Generated by Django 3.0.3 on 2020-06-29 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20200629_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessrecord',
            old_name='name',
            new_name='name_webpage',
        ),
    ]
